# Name of the experiment for saving files
experiment_name: baseline_light_mult_
save_folder: results/

# Define training strategy
training_strategy:
  niter: 50 # of iter at starting learning rate. Total #epochs is niter + niter_decay'
  niter_decay: 0 # of iter to linearly decay learning rate to zero
  is_train: True
  class_weight: True
  class_weight_cityscapes: False
  image_visualization: False

# model options
model:
  architecture: vgg16 #[options: 'vgg16', 'vgg16_bn', 'vgg16_guided', 'resnet18', 'vgg16_correlated']
  semantic: True
  pretrained: True
  correlation: True
  prior: False
  spade: '' #[options: 'encoder', 'decoder', 'both', '']
  num_semantic_classes: 19 # Actual training labels
diss_pretrained:
  load: False
  experiment_name: spade_both_instance_8_final # where checkpoints are stored
  save_folder: results/ # where checkpoints are stored
  which_epoch: best

# logger options
logger:
  results_dir: ./logs_light
  save_epoch_freq: 50 #frequency of saving checkpoints at the end of epochs

# loss options (remove tasks not needed)
loss:  CrossEntropyLoss

# optimization options
optimizer:
  algorithm: Adam # ['Adam' or 'SGD']
  # Define accordingly, e.g.
  parameters:
    lr: 1.e-4 # 1.e-4
    lr_policy: ReduceLROnPlateau
    patience: 10
    factor: 0.5
    weight_decay: 0.0000
    beta1: 0.5 # momentum term of adam
    beta2: 0.999 # momentum term of adam

# parameters for dataloaders
train_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/epfl/train
    #dataroot: /home/giancarlo/data/innosuisse/road_anomaly  #(only for quick debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: True
    normalize: True
    void: False
    light_data: True
    num_semantic_classes: 19
    is_train: True
  dataloader_args:
    batch_size: 8
    num_workers: 4
    shuffle: True
val_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader1:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/road_anomaly
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    roi: False
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader2:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_static
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    roi: True
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader3:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    roi: True
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader4:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_static
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    roi: False
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
img_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/visualization_imgs
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    flip: False
    normalize: True
    light_data: True
    void: False
    num_semantic_classes: 19
    is_train: True
  dataloader_args:
    batch_size: 10
    num_workers: 4
    shuffle: False
